=== jintrone/CCI-Shared-Code/testing-utils/src/main/resources/testExperiments.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://cci.mit.edu/simulation/testing/experiments" xmlns:exp="http://cci.mit.edu/simulation/testing/experiments" elementFormDefault="qualified">


    <element name="experiments">
        <complexType>
            <sequence>
                <element name="experiment" minOccurs="0" maxOccurs="unbounded">
                	<complexType>
                		<sequence>
                			
                			<element name="inputs">
                				<complexType>
                					<sequence>
                						<element name="input" minOccurs="1" maxOccurs="unbounded">
                							<complexType>
                								<attribute name="name" type="string" use="required" />
                							</complexType>
                						</element>
                					</sequence>
                				</complexType>
                			</element>
                			
                			<element name="outputs">
                				<complexType>
                					<sequence>
                						<element name="output" minOccurs="1" maxOccurs="unbounded">
                							<complexType mixed="true">
                								<attribute name="name" type="string" use="required" />
                							</complexType>
                						</element>
                					</sequence>
                				</complexType>
                			</element>
                		</sequence>
                		
                		<attribute name="id" type="string" use="required"/>
                	</complexType>
                </element>
            </sequence>
        </complexType>
    </element>
    
</schema>

=== jintrone/CCI-Shared-Code/pangaea-core/src/test/resources/testExperiments.xml
<?xml version="1.0" encoding="UTF-8"?>
<experiments xmlns="http://cci.mit.edu/simulation/testing/experiments" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://cci.mit.edu/simulation/testing/experiments testExperiments.xsd">
	<experiment id="1">
		<inputs>
			<input name="DEVELOPED_FF_START">2005</input>
			<input name="DEVELOPED_FF_TARGET">2050</input>
			<input name="DEVELOPED_FF_CHANGE">0.5</input>
			
			<input name="DEVELOPINGA_FF_START">2005</input>
			<input name="DEVELOPINGA_FF_TARGET">2050</input>
			<input name="DEVELOPINGA_FF_CHANGE">0.5</input>
			
			<input name="DEVELOPINGB_FF_START">2005</input>
			<input name="DEVELOPINGB_FF_TARGET">2050</input>
			<input name="DEVELOPINGB_FF_CHANGE">0.5</input>
			
			<input name="AFFORESTATION">0.2</input>
			<input name="DEFORESTATION">0.6</input>
			
		</inputs>
		<outputs>
			<output name="toString"><![CDATA[
CO2 Concentration:[[372.55188], [374.09433], [375.67938], [377.37146], [379.18866], [381.15274], [383.20328], [385.2267], [387.22852], [389.21188], [391.17914], [393.12732], [395.0489], [396.9433], [398.80997], [400.64902], [402.46143], [404.2485], [406.01212], [407.7544], [409.47742], [411.18436], [412.87857], [414.56158], [416.2346], [417.89874], [419.55508], [421.20438], [422.84732], [424.4845], [426.1164], [427.74814], [429.38873], [431.0398], [432.70068], [434.37076], [436.04947], [437.73633], [439.43094], [441.13287], [442.8418], [444.55893], [446.2863], [448.0233], [449.7693], [451.52393], [453.2867], [455.05725], [456.8353], [458.62042], [460.41248], [462.20963], [464.00958], [465.81238], [467.61826], [469.4272], [471.23932], [473.05463], [474.87323], [476.69516], [478.52042], [480.34976], [482.18414], [484.02344], [485.8676], [487.71667], [489.57062], [491.4293], [493.2928], [495.16107], [497.03397], [498.91177], [500.79477], [502.68292], [504.57617], [506.47446], [508.37778], [510.28604], [512.1993], [514.11743], [516.04047], [517.96674], [519.8937], [521.82153], [523.7504], [525.6804], [527.6117], [529.5444], [531.4786], [533.4144], [535.35205], [537.2913], [539.23267], [541.1761], [543.1216], [545.06915], [547.01904], [548.97107], [550.9254], [552.882], [554.841]]
BAU CO2 Concentration:[[372.551], [374.094], [375.679], [377.371], [379.188], [381.152], [383.229], [385.347], [387.507], [389.709], [391.954], [394.255], [396.635], [399.09], [401.62], [404.223], [406.898], [409.645], [412.464], [415.352], [418.312], [421.356], [424.509], [427.768], [431.132], [434.6], [438.17], [441.841], [445.614], [449.487], [453.46], [457.544], [461.756], [466.095], [470.559], [475.148], [479.861], [484.699], [489.66], [494.746], [499.956], [505.296], [510.779], [516.404], [522.17], [528.078], [534.128], [540.32], [546.654], [553.132], [559.753], [566.477], [573.237], [580.039], [586.886], [593.782], [600.73], [607.732], [614.791], [621.909], [629.088], [636.329], [643.632], [650.999], [658.432], [665.931], [673.499], [681.136], [688.844], [696.624], [704.477], [712.403], [720.401], [728.472], [736.617], [744.838], [753.134], [761.507], [769.958], [778.486], [787.094], [795.758], [804.441], [813.147], [821.876], [830.631], [839.412], [848.221], [857.059], [865.927], [874.827], [883.76], [892.729], [901.736], [910.781], [919.864], [928.986], [938.148], [947.35], [956.592], [965.875]]
CO2 Radiative Forcing:[[1.5854226], [1.6075274], [1.6301479], [1.6541901], [1.679891], [1.7075305], [1.7362355], [1.7644107], [1.79214], [1.8194728], [1.8464456], [1.8730239], [1.8991107], [1.9247042], [1.9498043], [1.9744185], [1.9985659], [2.0222692], [2.0455587], [2.0684676], [2.0910273], [2.1132824], [2.135281], [2.1570446], [2.178592], [2.199939], [2.2211022], [2.242092], [2.2629192], [2.2835934], [2.3041215], [2.3245697], [2.3450496], [2.3655818], [2.386157], [2.4067664], [2.4274025], [2.4480593], [2.4687307], [2.4894114], [2.510097], [2.5308018], [2.5515492], [2.5723314], [2.5931408], [2.6139715], [2.6348178], [2.6556742], [2.6765375], [2.6974022], [2.7182665], [2.7391088], [2.7599025], [2.780648], [2.8013492], [2.8220055], [2.842618], [2.863188], [2.8837159], [2.9042025], [2.9246488], [2.9450626], [2.9654539], [2.9858227], [3.0061681], [3.0264902], [3.0467885], [3.0670614], [3.0873103], [3.1075342], [3.127732], [3.1479065], [3.16806], [3.1881936], [3.2083051], [3.2283945], [3.2484627], [3.2685068], [3.2885284], [3.308526], [3.3285003], [3.3484335], [3.3682992], [3.3881013], [3.407841], [3.4275193], [3.4471388], [3.4667], [3.4862063], [3.5056574], [3.5250556], [3.5444012], [3.5636969], [3.582944], [3.6021423], [3.6212924], [3.640397], [3.6594546], [3.6784668], [3.6974337], [3.7163558]]
Cumulative emissions (CO2+N2O+CH4) rel. to 2005:[[-0.137398], [-0.12777473], [-0.113431625], [-0.08237644], [-0.047924284], [0.0], [-4.3652373E-4], [-9.3739707E-4], [-0.0014250994], [-0.0019001953], [-0.0023641898], [-0.0024622194], [-0.0025568623], [-0.0026489652], [-0.0027386218], [-0.0028264911], [-0.002912949], [-0.0029981842], [-0.0030825725], [-0.0031663962], [-0.003250032], [-0.0036567328], [-0.004045935], [-0.0044198027], [-0.00477937], [-0.0051265196], [-0.005462379], [-0.0057881726], [-0.0061047464], [-0.0064131357], [-0.0067144684], [-0.0070660394], [-0.007243095], [-0.0074071675], [-0.007558634], [-0.0076986225], [-0.007827886], [-0.0079469895], [-0.008056779], [-0.008157725], [-0.008250298], [-0.008240891], [-0.008227719], [-0.008210786], [-0.008190088], [-0.00816638], [-0.008139285], [-0.008109274], [-0.0080764415], [-0.008040786], [-0.0080026835], [-0.008178516], [-0.008351526], [-0.008521996], [-0.008689644], [-0.008855034], [-0.00901779], [-0.009178099], [-0.009336151], [-0.0094916625], [-0.009645104], [-0.009429759], [-0.009216954], [-0.009007065], [-0.008799528], [-0.008594813], [-0.008392544], [-0.008192911], [-0.007995628], [-0.0078006973], [-0.007608119], [-0.007352038], [-0.0070987786], [-0.0068483423], [-0.006600822], [-0.0063558416], [-0.006113778], [-0.0058742543], [-0.005637271], [-0.0054029217], [-0.005171207], [-0.0050655566], [-0.0049604713], [-0.004855856], [-0.004751617], [-0.0046478487], [-0.0045443624], [-0.0044414406], [-0.004338895], [-0.004236726], [-0.0041350275], [-0.0040005893], [-0.003866904], [-0.003733783], [-0.0036012265], [-0.0034693286], [-0.003337901], [-0.0032071322], [-0.0030769277], [-0.0029472876], [-0.0028182121]]
Developed countries fossil fuel emissions:[[3.888825], [3.8956776], [3.9204373], [3.9847486], [4.027011], [4.1619864], [4.1706553], [4.1686363], [4.1661925], [4.1633396], [4.1600866], [4.163233], [4.165635], [4.167332], [4.168363], [4.168758], [4.168547], [4.1677585], [4.166414], [4.1645374], [4.1621485], [4.1627564], [4.1626234], [4.16179], [4.160293], [4.1581635], [4.1554346], [4.152127], [4.148267], [4.143875], [4.138972], [4.136633], [4.147902], [4.1586757], [4.168987], [4.1788635], [4.1883388], [4.1974363], [4.2061777], [4.2145867], [4.222681], [4.2347355], [4.246327], [4.2574844], [4.2682385], [4.2786026], [4.288604], [4.2982597], [4.3075943], [4.3166165], [4.325344], [4.329383], [4.3333583], [4.337271], [4.341127], [4.344922], [4.348662], [4.35235], [4.355977], [4.35956], [4.3630857], [4.3688397], [4.3745255], [4.380134], [4.3856745], [4.3911424], [4.3965464], [4.401877], [4.4071484], [4.4123507], [4.4174914], [4.4232535], [4.428951], [4.4345818], [4.440154], [4.445662], [4.451109], [4.4564967], [4.4618263], [4.4670935], [4.472309], [4.47242], [4.4725304], [4.4726415], [4.472751], [4.472862], [4.4729724], [4.473078], [4.4731894], [4.4732985], [4.473406], [4.4737387], [4.4740696], [4.474404], [4.4747314], [4.475061], [4.4753885], [4.475712], [4.476039], [4.4763613], [4.4766817]]
Developing A countries fossil fuel emissions:[[1.8169781], [1.8661311], [1.9385136], [2.1489289], [2.423232], [2.6996448], [2.7071507], [2.7239168], [2.740188], [2.755982], [2.771319], [2.788855], [2.8057199], [2.82195], [2.837585], [2.8526547], [2.8671923], [2.8812242], [2.8947756], [2.9078736], [2.9205363], [2.9344072], [2.947712], [2.9604874], [2.9727647], [2.984577], [2.9959507], [3.0069084], [3.0174763], [3.0276732], [3.0375192], [3.0480025], [3.0528526], [3.0574837], [3.0619154], [3.0661557], [3.0702236], [3.0741274], [3.077879], [3.0814867], [3.0849583], [3.0906715], [3.0961578], [3.1014342], [3.1065128], [3.1114051], [3.1161213], [3.1206717], [3.1250677], [3.1293154], [3.133424], [3.1352537], [3.1370556], [3.1388283], [3.1405725], [3.1422887], [3.1439784], [3.145642], [3.1472807], [3.148893], [3.1504812], [3.1527002], [3.1548872], [3.1570437], [3.159172], [3.1612706], [3.1633396], [3.1653798], [3.1673944], [3.1693819], [3.1713421], [3.1735804], [3.1757934], [3.1779773], [3.1801348], [3.1822658], [3.1843715], [3.1864502], [3.188506], [3.190535], [3.192541], [3.1922536], [3.1919682], [3.1916833], [3.1913993], [3.1911173], [3.1908362], [3.1905563], [3.1902785], [3.1899998], [3.1897228], [3.1895373], [3.1893508], [3.1891663], [3.188982], [3.1887987], [3.188616], [3.188433], [3.1882536], [3.1880727], [3.1878934]]
